name: tp1-ej7
services:

  front:
    build: front/.
    image: facundol/tp1-ej7-front:latest
    ports:
      - 8080:8080/tcp
    container_name: front
    depends_on:
      - suma
      - calculo-pi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red-contenedores

  suma:
    build: back-suma/.
    image: facundol/tp1-ej7-suma:latest
    ports:
      - 9001:9001/tcp
    container_name: suma
    networks:
      - red-contenedores

  calculo-pi:
    build: back-PI/.
    image: facundol/tp1-ej7-calculo-pi:latest
    ports:
      - 9000:9000/tcp
    container_name: calculo-pi
    networks:
      - red-contenedores

networks:
  red-contenedores:
