# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: tp2-ej1-k8s-deploy
run-name: Kubernetes deploy (@${{ github.triggering_actor }})

on:
  push:
    branches:
      - pipeline-actions

jobs:
  k8s-deploy:
    name: Kubernetes deployment
    if: contains(github.event.head_commit.message, 'DEPLOY')
    runs-on: ubuntu-latest
    environment: pipeline-actions
    steps:

      # Checkout.
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala la CLI de Kubernetes.
      - name: Install kubectl
        working-directory: tp02/ej1/servidor/k8sd                                                                                                                                          
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          kubectl version --client
      
      # Despliega los objectos en la nube.
      - name: Deploy
        working-directory: tp02/ej1/servidor/k8sd                                                                                                                                          
        run: |
          echo "OK"

          # TODO: crear los secretos en Kubernetes y desplegar los objetos.