# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: tp2-ej1-terraform-destroy
run-name: Terraform destroy (@${{ github.triggering_actor }})

on:
  push:
    branches:
      - pipeline-actions

jobs:
  terraform-destroy:
    name: Terraform destroy
    if: contains(github.event.head_commit.message, 'DESTROY')
    runs-on: ubuntu-latest
    environment: pipeline-actions
    steps:

      # Selecciona la rama para.
      - name: Checkout code 
        uses: actions/checkout@v3

      # Instala y configura Terraform CLI.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Crea la infraestructura en la nube.
      - name: Terraform destroy
        working-directory: tp02/ej1/servidor/terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          ls -lah

          bucket_name="unlu-tf"

          prefix="gke/state"

          terraform init --reconfigure \
          --backend-config bucket=$bucket_name \
          --backend-config prefix=$prefix

          terraform destroy -lock=false --auto-approve